# Detection thresholds
AUTHENTICITY_THRESHOLD_HIGH = 0.75
AUTHENTICITY_THRESHOLD_MEDIUM = 0.60
AUTHENTICITY_THRESHOLD_LOW = 0.40

# File size limits (in MB)
MAX_IMAGE_SIZE_MB = 100
MAX_VIDEO_SIZE_MB = 500

# Analysis settings
MAX_VIDEO_FRAMES = 30
IMAGE_RESIZE_DIMENSION = 512

# Rate limiting
RATE_LIMIT_REGISTER = 3
RATE_LIMIT_LOGIN = 5
RATE_LIMIT_ANALYSIS = 10
RATE_LIMIT_WINDOW = 300  # 5 minutes

# Cache settings
CACHE_DURATION_SECONDS = 300

# Security
PASSWORD_MIN_LENGTH = 8
OTP_EXPIRY_MINUTES = 10
JWT_EXPIRY_HOURS = 24

# Database
DB_CONNECTION_TIMEOUT = 5000
DB_MAX_POOL_SIZE = 50
